spring:
  # thymeleaf配置
  thymeleaf:
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间,默认60000ms(10分钟)
      idle-timeout: 180000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间
      max-lifetime: 180000
      # 连接超时时间
      connection-timeout: 30000
      # 心跳连接,测试连接是否可用的查询语句
      connection-test-query: SELECT 1

#Mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 配置POJO别名
  type-aliases-package: com.mall.seckill.pojo

#Mybatis SQL打印(方法接口所在的,不是mapper.xml所在的包)
logging:
  level:
    com.mall.seckill.mapper: debug


